name: main

env:
  SERVER_USER: 'valen'
  working directory: C:\Users\valen\Desktop\Projets\cicd

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name: Checkout le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Installer les dépendances
        run: npm install

      - name: Exécuter les tests
        run: npm run test:ci

      - name: Vérifier le code
        run: npm run lint

      - name: Vérifier les vulnérabilités
        run: npm audit

  package:
    needs: tests
    runs-on: windows-latest
    steps:
      - name: Créer le répertoire du package
        run: mkdir -p server-package

      - name: Copier les fichiers pour le package
        run: cp -R ${{ github.workspace }}/server/* ${{ github.workspace }}/server-package/

      - name: Zipper le package
        run: 7z a ${{ github.workspace }}/server-package.zip ${{ github.workspace }}/server-package/*

      - name: Push du package
        uses: actions/upload-artifact@v2
        with:
          name: my-package
          path: ${{ github.workspace }}/server-package.zip

      - name: Créer une release GitHub
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
