name: main

defaults :
  run :
    working-directory : server

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name: Checkout le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Installer les dépendances
        run: npm install

      - name: Exécuter les tests
        run: npm run test:ci

      - name: Vérifier le code
        run: npm run lint

      - name: Vérifier les vulnérabilités
        run: npm audit

  package:
    needs: tests
    runs-on: windows-latest
    steps:
      - name: Checkout le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Installer les dépendances
        run: npm install
      

      - name: Créer le package
        run: npm run pack
        

      - name: Push du package
        uses: actions/upload-artifact@v2
        with:
          name: my-package
          path: server/*.tgz

      

  deploy:
          needs: package
          runs-on: windows-latest
          steps:
                  - name: Checkout le code
                    uses: actions/checkout@v4

                  - name: Installer Node.js
                    uses: actions/setup-node@v4
                    with: 
                     node-version: '20'
                     cache: 'npm'
                     cache-dependency-path: server/package-lock.json

                  - name: Installer les dépendances
                    run: npm install
                  - name: Télécharger le package
                    uses: actions/download-artifact@v2
                    with: 
                     name: my-package
                     path: server-package
        
                  - name: Extraire le package
                    run: |
                      