name: CI/CD Pipeline

env:
  SERVER_USER: 'root'
  SERVER_IP: '54.37.11.162'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14' # Remplacez par la version de Node.js souhaitée
          cache: 'npm'
          cache-dependency-path: chemin/vers/package-lock.json

      - name: Installer les dépendances
        working-directory: server # Remplacez "server" par votre répertoire contenant les dépendances
        run: npm install

      - name: Lint/Formatage
        working-directory: server # Remplacez "server" par votre répertoire contenant les fichiers à lint/formater
        run: npm run lint

      - name: Exécuter les tests unitaires
        working-directory: server # Remplacez "server" par votre répertoire contenant les tests unitaires
        run: npm run test:unit

      - name: Exécuter les tests d'intégration
        working-directory: server # Remplacez "server" par votre répertoire contenant les tests d'intégration
        run: npm run test:integration

      - name: Exécuter les tests E2E
        working-directory: server # Remplacez "server" par votre répertoire contenant les tests E2E
        run: npm run test:e2e

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v4

      - name: Déployer sur le serveur
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

        run: |
          New-Item -Path $env:USERPROFILE\.ssh -ItemType Directory -Force
          Set-Content -Path $env:USERPROFILE\.ssh\id_rsa -Value $env:SSH_PRIVATE_KEY
          ssh-keyscan -H $env:SERVER_IP | Out-File -Append -FilePath $env:USERPROFILE\.ssh\known_hosts
          Copy-Item -Path server -Destination "$env:SERVER_USER@$env:SERVER_IP:/var/www" -Recurse -Force
          ssh $env:SERVER_USER@$env:SERVER_IP "cd /var/www/server ; npm install --omit=dev"
          ssh $env:SERVER_USER@$env:SERVER_IP "cd /var/www/server ; pm2 startOrRestart ecosystem.config.js --env production ; pm2 save"
