name: main

env:
  SERVER_USER: 'root'
  SERVER_IP: '54.37.11.162'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout le code
        uses: actions/checkout@v4

      - name: Déployer sur le serveur
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir %USERPROFILE%\.ssh
          echo %SSH_PRIVATE_KEY% > %USERPROFILE%\.ssh\id_rsa
          scp -r ./server ${SERVER_USER}@${SERVER_IP}:/var/www
          ssh ${SERVER_USER}@${SERVER_IP} "cd /var/www/server && npm install --omit=dev"
          ssh ${SERVER_USER}@${SERVER_IP} "cd /var/www/server && pm2 startOrRestart ecosystem.config.js --env production && pm2 save"
