name : release GH 

env:
    SERVER_USER: 'valen'
    SERVER_IP: '192.168.1.38'

defaults :
    run :
        working-directory : server

on:
    workflow_dispatch : 
        inputs:
            version:
                description: "Version de l'application"
                required: true
                type: string

jobs:
    release:
        runs-on : windows-latest
        steps:
            - name: Créer une release GitHub
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: v{{inputs.version}}
                release_name: Release v{{inputs.version}}
                draft: false
                prerelease: false
              
         